# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    uses: cabify/javascript-actions/.github/workflows/npm_publish.yml@main
    with:
      tag: ${{ contains(github.ref_name,'beta') && 'beta' || 'latest' }}
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
