# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish canary package

on:
  workflow_run:
    branches-ignore:
      - 'main'
    workflows: ["Tests"]
    types:
      - completed
  push:
    tags:
      - 'v**-**'

jobs:
  publish-canary-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          tag: beta
          token: ${{ secrets.NPM_TOKEN }}
